### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by Den-Rimus** [AndroidDeveloperLB/AndroidJniBitmapOperations#12]
I got these results:
getJniResizedBmp [1498ms] 
getResizedBmp [443ms] 

(measurements are done using Jake Wharton's hugo library)

This is what getResizedBmp does:
https://gist.github.com/Den-Rimus/0595a88a9424e005c7f2

Image parameters are something around 3000+ x 2000+ downscale to 1365x1024 (height x width)

I understand that Bilinear Interpolation gives better quality that Java's stock methods, but are mine results somehow comparable with this lib author's?

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
Any updates on this? I'd love to see if this library really is faster (as it should be, since its C written) than the default Android methods.

**Comment by AndroidDeveloperLB** [comment]
@RaymondBakkerMoonlightMultimedia Sadly I can't import the project and work on it. Android Studio gives me a lot of issues when I try it. If you've successfully imported the project and can really edit the source code (of C/C++) and compile it, please show a step-by-step tutorial so that I could investigate this.

In any case, I'm not sure how much I can help optimizing it, as some of the time being used is probably for copying data between Java<->JNI "worlds" . This can be tested by just storing the data and retriving it. How much time does this part take ?

Also, about resizing, have you tried the NN method instead? it's supposed to be faster...

**Comment by FTExplore** [comment]
In my opinion, The most important advantage of  processing bitmap by jni is memory controlling. So I can ignore the speedy issue.

**Comment by AndroidDeveloperLB** [comment]
Indeed.
But, you have to remember that most of the heavy work here is the switching between Java and JNI "worlds". Once you are in JNI world, the work there should be very fast compared to Java world. 
So, if you have a very sophisticated and complex work to do in JNI, the whole total amount of time should be smaller than if you did all in Java. 

The main purposes of this library are:
1. demonstrate how to use bitmaps in JNI
2. allow to temporarily store bitmaps in JNI, with the possibility of caching
3. ability to handle too-large bitmap that if you had 2 of them might cause OOM.
