### ISSUE TITLE
Question about thread safety

### ISSUE THREAD

**Issue by ghost** [AndroidDeveloperLB/AndroidJniBitmapOperations#21]
First off, thanks for the great library!

I was wondering if the library was thread safe. I tried running some operations on a bunch of different bitmaps on different threads and got a crash in the library but I didn't analyze it all that much.

Cheers!
Justin

**Comment by AndroidDeveloperLB** [comment]
Thank you for trying out my tiny library.

About your question, I've never tried, but I think it depends on what you do. 
I think that if each thread uses its own JniBitmapHolder instance that work on a different bitmap object, it should be fine.
If you use the same bitmap for multiple threads, yet some of them recycle (free) the bitmap, others might try to read it and that's a bad thing.

In any case, I recommend that if large bitmaps are being handled, a single thread will be used for decoding, and another one will be used for JNI operations on the decoded bitmap (or one thread for both). 
The reason is that you are limited to the size of the heap for the decoding part.

I'd like to ask you something too:
How did you manage to import the project? as of Android-Studio, I couldn't import the project anymore. Not only that, but for some reason I have issues with writing the C/C++ code in Eclipse (it has plenty of errors). Only if I don't open the C/C++ files I can compile.

Also, BTW, I've heard Facebook also has its own image library, but I couldn't build it for some reason (link here: https://github.com/facebook/fresco ) .

**Comment by jcamp1** [comment]
Now that you mention it, I was using it an a list adapter where each row would spawn off an async task and we were caching images, so it's possible that multiple threads were trying to access the same bitmap. I'll have to explore that a bit...

I couldn't get your sample project to run, but I got the library to work. Here's what I did:
I copied the .cpp file into the appropriate jni directory in my own project, then copied your java class. After telling my project where to find the ndk, it compiled and worked without a hitch ;)

**Comment by AndroidDeveloperLB** [comment]
It worked on Android-Studio? You could even edit the CPP files and compile them?
Can you please put a step-by-step tutorial on my main page of the library?

**Comment by jcamp1** [comment]
Yeah I have it compiling and working (and it works really well!) in my Android Studio project. I imported the source code of your library which recompiles every time I do a full clean/compile :)  I'll try to get something up over the weekend, work is a bit crazy right now.

**Comment by AndroidDeveloperLB** [comment]
ok, please put a nice step-by-step on the main page of this repository. That would be awesome .
You are also welcomed to try my other repositories. I've published today another tiny one.

**Comment by jcamp1** [comment]
Hi,

Sorry I'm a bit late with this update, life's been a bit crazy. I'm not sure how to add this to the top of the project so I'll just include it in a separate comment. I've tested these steps and verified they work...

**Comment by jcamp1** [comment]
Here are the raw steps to get the JniBitmapOpertaionsLibrary working in your project. I was not able to get the library to compile from git, however I was successful in importing and building the code right in my own project.

Download and install the NDK
Make sure you have Android Studio set up so it knows where to look for the NDK. There is a file called local.properties that should be near the root of your project. In that file make sure there is the following line:

ndk.dir=/Full/path/to/your/ndk


For the purposes of clarity I'll use the following for my project values:

Project name: MyApplication
App Name: app


Steps to get the library imported and working:


Create the directory 
MyApplication / app / src / main / jni

Copy the file JniBitmapOperationsLibrary.cpp into the jni directory you just created.

In the java directory (MyApplication->app->src->main->java) create the new package:
com.jni.bitmap_operations

Copy the file JniBitmapHolder into the package you just created.

Inside the gradle file of the module you're importing this to (Not the top-level gradle file) add the following in the android->defaultConfig section:
```
	ndk {
            moduleName "JniBitmapOperationsLibrary"
            ldLibs "log",  "jnigraphics"
        }
```
Just to be explicit (because I hate tracking down confusing gradle stuff), in
MyApplication->app->build.gradle, my config looks like this:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.testapp.myapplication"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"

        ndk {
            moduleName "JniBitmapOperationsLibrary"
            ldLibs "log",  "jnigraphics"
        }

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.0.0'
}
```

Do a Gradle Sync
Clean the Project
Run the project
Bathe in the glory of the library :)

Enjoy!

**Comment by AndroidDeveloperLB** [comment]
It can't compile the C++ file, I think. It says:

D:\android\ndk\build\core\add-application.mk
Error:(199) *** Android NDK: Aborting...    .  Stop.
Error:Execution failed for task ':app:compileDebugNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android\ndk\ndk-build.cmd'' finished with non-zero exit value 2

Here's the app project I've made:
https://drive.google.com/file/d/0B-PZZGk2vPohVjZGSnRJcEtMUjA/
