### ISSUE TITLE
Out of memory?

### ISSUE THREAD

**Issue by vkislicins** [AndroidDeveloperLB/AndroidJniBitmapOperations#22]
```
         dalvikvm-heap  E  Out of memory on a 61968400-byte allocation.
              dalvikvm  I  "AsyncTask #5" prio=5 tid=37 RUNNABLE
                        I    | group="main" sCount=0 dsCount=0 obj=0x44f98008 self=0x7796a680
                        I    | sysTid=26270 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=2018684768
                        I    | state=R schedstat=( 2619259960 691612270 6938 ) utm=219 stm=42 core=2
                        I    at android.graphics.Bitmap.nativeCreate(Native Method)
                        I    at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
                        I    at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
                        I    at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
                        I    at com.jni.bitmap_operations.JniBitmapHolder.jniGetBitmapFromStoredBitmapData(Native Method)
                        I    at com.jni.bitmap_operations.JniBitmapHolder.getBitmap(JniBitmapHolder.java:88)
                        I    at com.jni.bitmap_operations.JniBitmapHolder.getBitmapAndFree(JniBitmapHolder.java:93)
```

**Comment by AndroidDeveloperLB** [comment]
What's the resolution of the bitmap? 
What's the heap memory size?
when you call "jniGetBitmapFromStoredBitmapData" it gets the bitmap data that is stored in the JNI "world" and converts it back to the Java "world", so now it's on the heap memory, which is quite limited.

I think you can get the heap memory size by calling :

    Runtime.getRuntime().maxMemory();

if the available memory cannot be larger-or-equal of the output bitmap's memory usage, you will get an out-of-memory error. 

According to the log, it tries to create a 61,968,400 bytes (~61MB) of a bitmap, which is quite large.

To avoid this, you can check the free memory usage, and resize the bitmap accordingly. Remember that the memory that the bitmap that's created here is 4*width*height. You can change my code so that each bitmap will take 2*width*height by using a different bitmap configuration, if you don't need transparency and don't care much about quality.

You can also have a special solution where you show only a part of the real bitmap, but this is quite a complex thing to do.

**Comment by AndroidDeveloperLB** [comment]
Please let me know if you understand this.

**Comment by vkislicins** [comment]
Runtime.getRuntime().maxMemory(): 201326592
H: 2952 W:5248

Unfortunately I need maximum possible quality as I'm building a camera app and the rotation is to compensate camera orientation.

It's weird that the phone is trying to take a 61mb picture.. So your advice would be to scale it to fit the heap?

**Comment by AndroidDeveloperLB** [comment]
1. It's weird that the max heap is 201MB, yet the device can't hold this bitmap. Is it possible you hold other huge bitmaps? If so, is it possible to free them ?

2. The resolution that you've written should take at least
4*2952*5248 = 61,968,384 bytes, which is similar to what you got on the logs.
If you change my code as I've mentioned, you can reduce it by 2, meaning about:
2*2952*5248 = 30,984,192 bytes, which is ~30MB.
This is possible by using "RGB_565" config, as written here:
http://developer.android.com/reference/android/graphics/Bitmap.Config.html
You should use it only for images that don't have transparency. Usually you can't tell the difference in quality.

3. About the quality, using the normal Bitmap class mean that it has to be in the heap memory, so if you use this method, you are limited (sorry).

4. Maybe there are other libraries out there that could help you with this. 

5. Instead of calculating of the free memory (though it is a better solution), another method could be to use try-catch with the Out-Of-Memory exception handling inside a while(true) loop, so that each time it fails, it will resize the output bitmap by some factor (maybe by 2). 

6. And last, you can request the app to have a larger heap. by using android:largeHeap="true" inside the manifest. Do note that it doesn't promise you anything:
http://developer.android.com/reference/android/R.styleable.html#AndroidManifestApplication_largeHeap 
Google has some lectures that (some of them) are about bitmaps since HoneyComb. Maybe you should watch them:
https://www.youtube.com/watch?v=_CruQY55HOk
https://www.youtube.com/watch?v=sTx-5CGDvM8

**Comment by vkislicins** [comment]
Thanks for such a great response!! Plenty of options to consider, I really appreciate your help!

**Comment by AndroidDeveloperLB** [comment]
You're welcomed.

Do note that no matter what you choose to do, you have to consider that some devices do not have huge amounts of memory, so you have to have some fallbacks.

BTW, the same issue exist even on popular apps, like web browsers. Most web browsers on Android store all of the current page's content on the memory, so if you have a low-end device and a heavy website, the website could crash the web browser. Here's a sample of a heavy website:
http://imgur.com/a/GPlx4?desktop=1

Also, about the Google IO video, I am sure that there is another one, but I don't remember its name. They told about what's new on Honeycomb, and one of the changes was about how bitmaps are stored (which is the heap).

**Comment by vkislicins** [comment]
In the end it helped to ```recycle()``` my bitmap after storing it with your library but before getting it back to Java world. Obviously still need to add handling for smaller heaps but that's already a step forward!

**Comment by AndroidDeveloperLB** [comment]
Yes, it's advised to recycle huge bitmaps before creating new ones.
If your previous bitmap tool 61 MB too, this means that together with the new one, you have 122MB of used memory at the same time.
Still less than ~200MB though.
