### ISSUE TITLE
About opacity bitmap

### ISSUE THREAD

**Issue by dockusan** [AndroidDeveloperLB/AndroidJniBitmapOperations#25]
Could you write function set alpha (opacity) for bitmap?
Because In Android I must create bitmap when set opacity for bitmap?

**Comment by AndroidDeveloperLB** [comment]
Sadly I've failed again and again to import the project into Android Studio and make it compile and work again.
About opacity, I think you can either directly change the bitmap data itself on Java, or even use Renderscript. Try out this sample:
https://github.com/xrigau/renderscripting
Needed changes:
1. make it change the input itself (meaning the input bitmap will also be the output), instead of creating a new one that has the output.
2. Instead of grayscale, change the alpha channel of each pixel to what you need.

**Comment by dockusan** [comment]
Thank for you reply.
I import to eclipse and it's works.
I want function write by JNI and make function as: jniHolder.makeAlpha(int alpha);

**Comment by AndroidDeveloperLB** [comment]
Try Renderscript. I'm sure it will be much better than my own code : shorter and faster.

**Comment by dockusan** [comment]
thank you. I will try

**Comment by AndroidDeveloperLB** [comment]
@dockusan Another interesting library that's similar to what I do is this one:
https://github.com/suckgamony/RapidDecoder

They actually even allow to decode the image via JNI, so it's probably faster too.

**Comment by dockusan** [comment]
Thank you for your suggest. I will check that library.
