### ISSUE TITLE
Out of Memory before save image to JNI memory

### ISSUE THREAD

**Issue by cuong292** [AndroidDeveloperLB/AndroidJniBitmapOperations#39]
Hi,first of all,thank you for the greate knowledge about JNI memory.But i just wonder that in your example `final Bitmap b = BitmapFactory.decodeResource(getResources(), IMAGE_RESID_TO_TEST);` is using the heap memory to load the bitmap 1st and then save the bitmap into the JNI memory.And if the bitmap is huge so it will throw the out of memory exception.I know that it can use BitmapOptions to scale the image to a smaller size,but is there any way to check the bitmap is outof(heap)memory before decode it?

**Comment by AndroidDeveloperLB** [comment]
Starting from some Android version (I think 8.0), bitmaps load in the total RAM of the device, like on JNI, and not on the heap.
This means OOM is very hard to reach, and in fact if you really try (meaning you try to load a lot of bitmaps or large ones that will fill the RAM), you will get a different error instead that as I remember is impossible to catch. I wrote about this here:

https://stackoverflow.com/q/48091403/878126

In order to estimate the total bytes that a bitmap takes, use the BitmapOptions together with how you plan to get it.
If you use the normal, default configurations, it should be this calculation:

`minimalEstimatedBitmapSizeInBytes = bitmapWidth*bitmapHeight*4`

The "4" is because each pixel takes 4 bytes. On some configurations it takes differently.

**Comment by cuong292** [comment]
thanks!! do u have any Q&A page or contact email.I saw that you are deep understand about Android system.Please give me any contact to ask question.I will not spam like hundred questions just the one i really cant find on the stack overflow etc...thank you

**Comment by AndroidDeveloperLB** [comment]
No. You can use StackOverflow.
I don't handle this repository anymore. I forgot how to even use JNI, and it probably changed on Android Studio and became easier.
